app/models.py
from app import db
from . import login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash,check_password_hash

@login_manager.user_loader
def load_user(user_id):
    return Users.query.get(int(user_id))

class Users(UserMixin,db.Model):
    __tablename__='users'
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(50), unique=True, index=True)
    email = db.Column(db.String(255), unique=True)
    password_hash = db.Column(db.String())
    pitches = db.relationship('Comments', backref='user', lazy=True)
    comments = db.relationship('Pitch', backref='user', lazy=True)

    @property
    def password(self):
        raise AttributeError('You cannnot read the password attribute')
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)
    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f'{self}'

class Pitch(db.Model):
    __tablename__ ='pitches'
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String())
    category = db.Column(db.String())
    content = db.Column(db.String())
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))


    @classmethod
    def get_pitches(cls):
        return Pitch.query.all()

    @classmethod
    def get_pitch(cls,pitch_id):
        return Pitch.query.filter_by(id=pitch_id).first()

    @classmethod
    def get_user_pitches(cls,user_id):
        return Pitch.query.filter_by(user_id=user_id).all()
        # pitches = Pitch.get_user_pitches(current_user.id)

class Comments(db.Model):
    __tablename__='comments'
    id = db.Column(db.Integer,primary_key=True)
    comment = db.Column(db.String()) 
    pitch_id = db.Column(db.Integer, db.ForeignKey('pitches.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    @classmethod
    def get_comments(cls,id):
        return Comments.query.filter_by(pitch_id=id)

class Reactions(db.Model):
    __tablename__='reactions'
    id = db.Column(db.Integer,primary_key=True)
    reaction = db.Column(db.String(10))
    pitch_id = db.Column(db.Integer,db.ForeignKey('pitches.id'))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required

class PitchForm(FlaskForm):

    title = StringField('Title',validators=[Required()])
    content = TextAreaField('Pitch', validators=[Required()])
    category = SelectField('Category', choices=[('quote', 'quote'), ('education', 'education'), ('business', 'business')],
                           validators=[Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    comment = StringField('Comment', validators=[Required()])
    submit = SubmitField('Post')


class Vote(FlaskForm):
    submit = SelectField('Like')


class UpdateProfile(FlaskForm):
    bio = TextAreaField('bio', validators=[Required()])
    submit = SubmitField('Post')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import Config,config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager


bootstrap = Bootstrap()
login_manager = LoginManager()
login_manager.session_protection = 'srong'
login_manager.login_view = 'auth.login'

db = SQLAlchemy()
def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(Config)
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # Initializing blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/accounts')


    # Will add the views and forms

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import forms,views

app/main/views.py
from flask import render_template, redirect,url_for
from . import main
from .forms import PitchForm, CommentForm, UpdateProfile
from ..models import *
from flask_login import current_user,login_user,login_required
from app  import db

@main.route('/')
def index():
    pitches = Pitch.get_pitches()
    title = 'Home'
    return render_template('index.html', pitches=pitches,title=title)

@main.route ('/new-pitch', methods =['GET','POST'])
def new_pitch():
    form = PitchForm()
    if form.validate_on_submit():
        title = form.title.data
        category = form.category.data
        content = form.content.data

        pitch = Pitch(title=title,category=category,user_id=current_user.id, content=content)
        db.session.add(pitch)
        db.session.commit()
        return redirect(url_for('main.new_pitch'))
    return render_template('new-pitch.html',form=form)

@main.route('/pitch/<int:id>',methods=['GET','POST'])
def pitch(id=None):
    if id:
        commentform=CommentForm()
        pitch = Pitch.get_pitch(id)
        comments = Comments.get_comments(id)

        if commentform.is_submitted():
            comment = Comments(comment=commentform.comment.data,user_id=current_user.id,pitch_id=id)
            db.session.add(comment)
            db.session.commit()
            return render_template('single-pitch.html',title=f'Pitch {id}',pitch=pitch,comments=comments,commentform=commentform)

        return render_template('single-pitch.html',title=f'Pitch {id}',pitch=pitch,comments=comments,commentform=commentform)

    return redirect(url_for('main.index'))

@main.route('/profile')
def profile():
     pitches = Pitch.get_user_pitches(current_user.id)

     return render_template('profile.html', pitches=pitches)

app/templates/base.html
{% extends 'bootstrap/base.html' %}
{% block styles %}
<link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">
{% endblock %}
{% block navbar%}
    {% include 'navbar.html' %}
{% endblock %}

{% block content %}

{% endblock %}

{% block scripts %}
<script src="{{url_for('static',filename='js/jquery-3.4.1.min.js')}}"></script>
<script src="{{url_for('static',filename='js/bootstrap.min.js')}}"></script>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}
{% block content %}
<div class="container">
    <div class="row py-3">
    {{ macro.display_pitches(pitches) }}        
    </div>
</div>
{% endblock %}

app/templates/macros.html
{% macro display_pitches(pitches) %}
    {% for pitch in pitches %}
    <div class="col-sm-12 col-md-6 p-2">
            <div class="card">
                <div class="card-body">
                    <div class="card-title h4">{{ pitch.title }}</div>
                    <div class="card-subtitle h6 text-primary">{{pitch.user.username}}</div>
                    <div class="card-text">
                        {{pitch.content}}
                    </div>
                    <a href="{{ url_for('main.pitch', id=pitch.id ) }}" class="btn btn-sm btn-primary w-100">View Pitch</a>
                </div>
            </div>
        </div>
    {% endfor %}
{% endmacro %}

{% macro display_comments(comments) %}
    {% for comment in comments %}
    <div class="col-sm-12 p-1">
            <div class="card border-bottom p-0">
                <div class="card-body py-0">
                    <div class="card-text">
                        <span class="font-weight-bold">@{{comment.user.username}} - </span><span class="font-italic">
                            {{comment.comment}}</span>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endmacro %}

app/templates/navbar.html
<nav class="navbar navbar-dark bg-dark">
    <ul class="nav">
        <li class="nav-item">
            <a href="/" class="nav-link">HOME</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
            <a href="{{url_for('main.new_pitch')}}" class="nav-link">NEW PITCH</a>
        </li>
        {% endif %}
    </ul>
    <ul class="nav navbar-right">
        
        {% if current_user.is_authenticated %}
        <li class="nav-item">
            <a href="{{url_for('main.profile')}}" class="nav-link p-2 border rounded ">Profile</a>
        </li>
        <li class="nav-item">
            <a href="{{url_for('auth.logout')}}" class="nav-link p-2 border rounded mx-1">Logout
            </a>
        </li>
        {% else %}
        <li class="nav-item">
                <a href="{{url_for('auth.login')}}" class="nav-link p-2 border rounded ">Login</a>
        </li>
        {% endif %}
    </ul>
</nav>

app/templates/new-pitch.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-6">
            <form action="" method="POST" class="form-horizontal">
                <h3>New pitch</h3>
                <div class="form-group">
                    {{form.csrf_token}}
                    {{form.title.label}}
                    {{form.title(class='form-control',placeholder='Pitch title')}}
                </div>
                <div class="form-group">
                    {{form.category.label}}
                    {{form.category(class='form-control')}}
                </div>

                <div class="form-group">
                    {{form.content.label}}
                    {{form.content(class='form-control',placeholder='Pitch Description/Content')}}
                    </div>
                    {{form.submit(class='btn btn-info')}}
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-sm-3">
            <h8>{{current_user.username}}</h8>
        </div>
        <div class="col-sm-6 row justify-content-center">
            <div class="card">
                <img src="{{url_for('static',filename='images/user.png')}}"  class="img-thumbnail profile-image">
            </div>
        </div>
        <div class="col-sm-3">
            {{current_user.email}}
        </div>
    </div>
    <h3 class="text-center">My Pitches</h3> <hr>
    <div class="row">
        {{macro.display_pitches(pitches)}}
    </div>
</div>
{% endblock %}

app/templates/single-pitch.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-sm-7 p-2">
            <div class="card">
                <div class="card-body">
                    <div class="card-title h3">{{pitch.title}}</div>
                    <div class="card-subtitle h5">
                        <a href="#" class="card-link"> @{{pitch.user.username}}</a>
                    </div>
                    <hr>
                    <div class="card-text">
                        {{pitch.content}}
                    </div>
                    <div class="footer btn-group">
                        <button class="btn btn-sm btn-success">Like
                            <span class="badge badge-light">2</span>
                        </button>
                        <button class="btn btn-sm btn-info">Dislike
                            <span class="badge badge-light">2</span>
                        </button>

                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-5">
            <h3> Comments</h3>
            <form action="" method="POST" class="form-inline">
                <div class="form-group">
                    {{commentform.csrf_token}}
                    {{commentform.comment(class="form-control",placeholder="Comment...")}}
                    {{commentform.submit(class="btn btn-info mx-1")}}
                </div>
            </form>

            <hr>
            <div class="row">
                {{macro.display_comments(comments)}}
            </div>
        </div>
    </div>
</div>
{% endblock %}